CoatColour.destroy_all
Breed.destroy_all
Cat.destroy_all


# Breeds
burmese = Breed.create!(name: "Burmese")
exotic = Breed.create!(name: "Exotic")
mandalay = Breed.create!(name: "Mandalay")
persian = Breed.create!(name: "Persian")

# Coat Colours
black = CoatColour.create!(name: "Black")
black_bicolour = CoatColour.create!(name: "Black Bicolour")
blue = CoatColour.create!(name: "Blue")
blue_bicolour = CoatColour.create!(name: "Blue Bicolour")
bluecream = CoatColour.create!(name: "Bluecream")
bluecream_bicolour = CoatColour.create!(name: "Bluecream Bicolour")
bluecream_point = CoatColour.create!(name: "Bluecream Point")
blue_harlequin = CoatColour.create!(name: "Blue Harlequin")
blue_tabby = CoatColour.create!(name: "Blue Tabby")
bluepoint = CoatColour.create!(name: "Bluepoint")
brown_tabby = CoatColour.create!(name: "Brown Tabby")
chocolate = CoatColour.create!(name: "Chocolate")
chocolate_bicolour = CoatColour.create!(name: "Chocolate Bicolour")
chocolate_tortie = CoatColour.create!(name: "Chocolate Tortie")
cinnamon = CoatColour.create!(name: "Cinnamon")
cinnamon_tabby = CoatColour.create!(name: "Cinnamon Tabby")
cream = CoatColour.create!(name: "Cream")
cream_bicolour = CoatColour.create!(name: "Cream Bicolour")
ebony = CoatColour.create!(name: "Ebony")
ebony_tabby = CoatColour.create!(name: "Ebony Tabby")
lilac = CoatColour.create!(name: "Lilac")
lilac_bicolour = CoatColour.create!(name: "Lilac Bicolour")
lilacpoint = CoatColour.create!(name: "Lilacpoint")
red_tabby = CoatColour.create!(name: "Red Tabby")
red_tabby_bicolour = CoatColour.create!(name: "Red Tabby Bicolour")
redpoint = CoatColour.create!(name: "Redpoint")
seal_tabby_point = CoatColour.create!(name: "Seal Tabby Point")
seal_tortie_point = CoatColour.create(name: "Seal Tortie Point")
ticked_tabby = CoatColour.create!(name: "Ticked Tabby")
tortoiseshell = CoatColour.create!(name: "Tortoiseshell")
tortoiseshell_bicolour = CoatColour.create!(name: "Tortoiseshell Bicolour")

# Cats
user = User.find 1

top = Cat.create!(name: "Martes Top Gun", breed: persian, coat_colour: black, user: user)
betsy = Cat.create!(name: "Askari Heavens T Betsy", user: user)
yu = Cat.create!(name: "Askari Here's Looking At Yu Kid", user: user)
gee = Cat.create!(name: "Askari Golly Gosh N' Gee Whiz", breed: exotic, coat_colour: tortoiseshell, user: user, sire: top, dam: betsy)
flash = Cat.create!(name: "Askari Zee Flashie Red Bear", breed: exotic, coat_colour: red_tabby, user: user, sire: yu, dam: gee)
particular = Cat.create!(name: "Preview Most Particular (Imp Aust)", breed: persian, coat_colour: black, user: user)
johnny = Cat.create!(name: "Bolos Johnny Lee", user: user)
fancy = Cat.create!(name: "Bolos Fancy", user: user)
pure = Cat.create!(name: "Purest Phenonmonen (Imp USA)", breed: persian, user: user, sire: johnny, dam: fancy)
blucream = Cat.create!(name: "Askari I'z Blu Wifa Bit O'Cream", breed: exotic, coat_colour: bluecream, user: user, sire: flash, dam: particular)
madison = Cat.create!(name: "Askari Dashin Bit O'Stuff", breed: exotic, coat_colour: blue, user: user, sire: pure, dam: blucream)
heart = Cat.create!(name: "Sunnyway Place NM' Heart", breed: persian, coat_colour: blue_bicolour, user: user)
gussie = Cat.create!(name: "Askari The Delectable Miss Gussie", breed: persian, user: user)
dash = Cat.create!(name: "Askari Flash Wifa Spot Of Dash", breed: exotic, coat_colour: blue_bicolour, user: user, sire: flash, dam: heart)
mickey = Cat.create!(name: "Askari Hairy McKerrie", breed: persian, coat_colour: blue_bicolour, user: user, sire: dash, dam: gussie)
spot = Cat.create!(name: "Askari Blu Spot Ona White Cloud", breed: persian, coat_colour: blue_harlequin, user: user, sire: dash, dam: gussie)

tweetie = Cat.create!(name: "Rosimorn Tweetie Pie", breed: exotic, coat_colour: tortoiseshell, user: user)
jackson = Cat.create!(name: "Jiachus Jackson Brown", breed: persian, coat_colour: chocolate, user: user)
cindy = Cat.create!(name: "Jady Cindy Sue", breed: persian, coat_colour: bluepoint, user: user)
bronze = Cat.create!(name: "Arsenios Touch Of Bronze", breed: mandalay, coat_colour: cinnamon_tabby, user: user)
greta = Cat.create!(name: "Atacat Greta Garbo (Gen 3)", breed: mandalay, coat_colour: ebony, user: user)
tonto = Cat.create!(name: "Lessentine Tontosang", breed: burmese, coat_colour: lilac, user: user)
mata = Cat.create!(name: "Rafoej Mata (Gen 2)", breed: mandalay, coat_colour: ticked_tabby, user: user)
ice = Cat.create!(name: "Fashfelene For His Ice Only", breed: persian, coat_colour: blue_bicolour, user: user)
charisma = Cat.create!(name: "Vondeen's Charisma of Fashfelene", breed: persian, coat_colour: cream_bicolour, user: user)
time = Cat.create!(name: "One More Time V Dreilinien (Ger)", breed: persian, coat_colour: cream, user: user)
lucy = Cat.create!(name: "Foxy I Lav Lucy Of Pirayas (Imp USA)", breed: persian, coat_colour: lilac, user: user)
donegal = Cat.create!(name: "Shirlim Lynx of Donegal", breed: persian, coat_colour: seal_tabby_point, user: user)
katalina = Cat.create!(name: "Shirlim My Katalina", breed: persian, coat_colour: bluecream_point, user: user)
soo = Cat.create!(name: "Myriddan Soolaimon", breed: persian, coat_colour: brown_tabby, user: user)
delite = Cat.create!(name: "Shelcraig Magics Delite", breed: persian, coat_colour: seal_tortie_point, user: user)
magnum = Cat.create!(name: "Jady Magnum (Imp Aust)", breed: persian, coat_colour: chocolate, user: user, sire: jackson, dam: cindy)
unforgettable = Cat.create!(name: "Rafoej Unforgettable (Gen 3)", breed: mandalay, coat_colour: ebony_tabby, user: user, sire: tonto, dam: mata)
rose = Cat.create!(name: "Atacat Leyla Rose", breed: mandalay, coat_colour: cinnamon, user: user, sire: bronze, dam: greta)
lav = Cat.create!(name: "Pirayas Lav Me Do (Imp Sweden)", breed: persian, coat_colour: lilacpoint, user: user, sire: time, dam: lucy)
ianina = Cat.create!(name: "Rosimorn Ianina", breed: persian, coat_colour: chocolate_tortie, user: user, sire: lav, dam: tweetie)
smudge = Cat.create!(name: "Fashfelene I Gotta Smudge (Imp Can)", breed: persian, coat_colour: bluecream_bicolour, user: user, sire: ice, dam: charisma)
man = Cat.create!(name: "Myriddan Solitary Man", breed: persian, coat_colour: redpoint, user: user, sire: soo, dam: delite)
lynx = Cat.create!(name: "Shirlim Lynx of Killarney", breed: persian, coat_colour: seal_tabby_point, user: user, sire: donegal, dam: katalina)
ustinov = Cat.create!(name: "Atacat Ustinov", breed: mandalay, coat_colour: cinnamon, user: user, sire: unforgettable, dam: rose)
apple = Cat.create!(name: "Rosimorn Apple Tart", breed: persian, coat_colour: chocolate, user: user, sire: magnum, dam: ianina)
made = Cat.create!(name: "Ozki All Made Up (Imp Aust)", breed: persian, coat_colour: seal_tabby_point, user: user, sire: man, dam: lynx)
bluebell = Cat.create!(name: "Rosimorn Yusta Bluebell", breed: persian, coat_colour: blue, user: user, sire: lav, dam: smudge)
nostradamus = Cat.create!(name: "Rosimorn Nostradamus", breed: persian, coat_colour: blue_tabby, user: user, sire: made, dam: bluebell)
lulu = Cat.create!(name: "Rosimorn Lulubelle (Gen 1)", breed: exotic, coat_colour: chocolate, user: user, sire: ustinov, dam: apple)
phoebe = Cat.create!(name: "Rosimorn Fancy That (Gen 2)", breed: exotic, coat_colour: lilac, user: user, sire: nostradamus, dam: lulu)
